### ISSUE TITLE
IncompleteReadError on using serverless-iopipe-layer 

### ISSUE THREAD

**Issue by MMuthukrishna** [iopipe/serverless-iopipe-layers#22]
IncompleteReadError on using serverless-iopipe-layer

```
0 read, but total bytes expected is 7536.: IncompleteReadError
Traceback (most recent call last):
File "/opt/python/iopipe/agent.py", line 163, in wrapped
raise e
File "/opt/python/iopipe/agent.py", line 145, in wrapped
result = func(event, context)
File "/opt/python/iopipe/handler.py", line 12, in wrapper
return get_wrapped_handler()(event, context)
File "/var/task/handler.py", line 98, in <function_name>
manifest = json.loads(s3_object_body.read().decode('utf-8'))
File "/var/runtime/botocore/response.py", line 82, in read
self._verify_content_length()
File "/var/runtime/botocore/response.py", line 134, in _verify_content_length
expected_bytes=int(self._content_length))
botocore.exceptions.IncompleteReadError: 0 read, but total bytes expected is 7536.
```

**Comment by kolanos** [comment]
@MMuthukrishna Can I get some example code to replicate? And which Python runtime is this?

**Comment by MMuthukrishna** [comment]
Sorry , I won't be able to share the sample code to replicate this issue
for the next two days , I will share it by Monday 17 Jun

**Comment by kolanos** [comment]
@MMuthukrishna What was the resolution?

**Comment by MMuthukrishna** [comment]
I couldn't replicate this
it is a lambda function triggered by cloudwatch logs, to execute copy
command on a redshift table.
It's difficult to replicate it.
